import { defineConfig, devices } from '@playwright/test';
import 'dotenv/config';

// Playwright here is the thin wrapper described in the architecture doc
// (Section J): one test.describe per claim, one test.step per section,
// a single assertion ("no CRITICAL/HIGH unexpected differences"). The
// reconciliation report generated by src/reporting is the primary output;
// this config exists to get trace/video/screenshot tooling for free on any
// claim that fails, not to drive hundreds of thousands of expect() calls.
export default defineConfig({
  testDir: './tests',
  timeout: 15 * 60 * 1000, // one claim walks two full environments; give it room
  expect: { timeout: 30 * 1000 },
  fullyParallel: true,
  // Claim-level concurrency is governed by WORKERS via BatchRunner, not by
  // Playwright's own worker pool, so the two must not multiply against each
  // other. Keep Playwright's own workers at 1 and let BatchRunner own the
  // fan-out (Section L).
  workers: 1,
  retries: 0, // retries are handled per-section inside the orchestrator (Section M), not by re-running the whole claim
  reporter: [
    ['list'],
    ['html', { open: 'never', outputFolder: 'playwright-report' }],
  ],
  use: {
    headless: true,
    ignoreHTTPSErrors: true,
    actionTimeout: 45 * 1000,
    navigationTimeout: 45 * 1000,
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
    video: 'off',
  },
  projects: [
    { name: 'chromium', use: { ...devices['Desktop Chrome'] } },
  ],
});
